### ISSUE TITLE
always redirect to homepage

### ISSUE THREAD

**Issue by centoasa** [oneall/social-login-prestashop#18]
https://www.100asa.it/?return_to=https%3A%2F%2Fwww.100asa.it%2Fit%2Flogin%3Fcreate_account%3D1
my prestashop is 1.7.5
this issue happens with login or create account

**Comment by baycii** [comment]
> https://www.100asa.it/?return_to=https%3A%2F%2Fwww.100asa.it%2Fit%2Flogin%3Fcreate_account%3D1
> my prestashop is 1.7.5
> this issue happens with login or create account

Please how did u fix it ?

**Comment by JoseManuelPedraja** [comment]
I have the same error with
Prestashop 8.1.2
OneAll Module v5.0.0
PHP 8.1
the error
https://mydomain.com/?return_to=https%3A%2F%2Fmydomain.com%2End-session

and log:

PHP message: PHP Deprecated: The hook "top" is deprecated, please use "displayTop" instead in module "sociallogin". in /home/mydomain/web/mydomain.com/public_html/classes/Hook.php on line 921', referer: https://mydomain.com/modules/ybc_blog_free/views/css/font-awesome.css
AH01071: Got error 'PHP message: PHP Warning: Attempt to read property "id_category_default" on null in /home/mydomain/web/mydomain.com/public_html/controllers/front/ProductController.php on line 1333PHP message: PHP Warning: Attempt to read property "name" on null in /home/mydomain/web/mydomain.com/public_html/controllers/front/ProductController.php on line 1353PHP message: PHP Fatal error: Uncaught Error: Call to a member function getAttributeCombinations() on null in /home/mydomain/web/mydomain.com/public_html/controllers/front/ProductController.php:1092\nStack trace:\n#0 /home/mydomain/web/mydomain.com/public_html/controllers/front/ProductController .php(1045): ProductControllerCore->tryToGetAvailableIdProductAttribute(0)\n#1 /home/mydomain/web/mydomain.com/public_html/controllers/front/ProductController.php(1354): ProductControllerCore->getIdProductAttributeByRequest()\n# 2 /home/mydomain/web/mydomain.com/public_html/classes/controller/FrontController.php(1822): ProductControllerCore->getBreadcrumbLinks()\n#3 /home/mydomain/web/mydomain.com/public_html/classes/ controller/FrontController.php(514): FrontControllerCore->getBreadcrumb()\n#4 /home/mydomain/web/mydomain.com/public_html/classes/controller/FrontController.php(572): FrontControllerCore->assignGeneralPurposeVariables()\ n#5 /home/mydomain/web/mydomain.com/public_html/controllers/front/ProductController.php(465): FrontControllerCor...', referer: https://mydomain.com/
